"use client";

import { useEffect, useReducer, useState } from "react";
import { useCopilotAction, useCopilotReadable } from "@copilotkit/react-core";
import {
  CARD_COLORS,
  NewCardRequest,
  Transaction,
} from "@/app/api/v1/data";
import { CreditCardDetails } from "@/components/credit-card-details";
import { PartialBy } from "@/lib/type-helpers";
import {
  filterTransactionByTitle,
  filterTransactionsByCardLast4,
  filterTransactionsByPolicyId,
  randomDigits,
} from "@/lib/utils";
import useCreditCards from "@/app/actions";
import { useAuthContext } from "@/components/auth-context";
import { AddCardDropdown } from "@/components/add-card-dropdown";
import { TransactionsList } from "@/components/transactions-list";
import { ChangePinDialog } from "@/components/change-pin-dialog";
import { useSearchParams } from "next/navigation";
import { CardsPageOperations } from "@/components/copilot-context";
import { useCopilotChatSuggestions } from "@copilotkit/react-ui";
import { PERMISSIONS } from "@/app/api/v1/permissions";

interface ChangePinState {
  newPin: string;
  dialogOpen: boolean;
  cardId: string | null;
  loading: boolean;
}

export default function Page() {
  const { currentUser } = useAuthContext();
  const searchParams = useSearchParams();
  const operation = searchParams.get("operation") as CardsPageOperations | null;
  const [state, dispatch] = useReducer<
    React.Reducer<ChangePinState, Partial<ChangePinState>>
  >(
    (state: ChangePinState, payload: Partial<ChangePinState>) => ({
      ...state,
      ...payload,
    }),
    { newPin: "", dialogOpen: false, cardId: null, loading: false }
  );
  const [hitlEnabled, setHitlEnabled] = useState(false);
  const {
    cards,
    policies,
    transactions,
    addNewCard,
    changePin,
    assignPolicyToCard,
    addNoteToTransaction,
    changeTransactionStatus,
  } = useCreditCards();

  useEffect(() => {
    const operationNameToMethod: Partial<
      Record<CardsPageOperations, () => void>
    > = {
      [CardsPageOperations.ChangePin]: () => dispatch({ dialogOpen: true }),
    };

    if (!operation || !Object.values(CardsPageOperations).includes(operation))
      return;
    operationNameToMethod[operation]?.();
  }, [operation]);

  const handleChangePinSubmit = async ({
    pin,
    cardId,
  }: {
    pin?: string;
    cardId?: string;
  }) => {
    dispatch({ loading: true });
    await changePin({
      pin: pin ?? state.newPin,
      cardId: cardId ?? state.cardId!,
    });
    dispatch({ loading: false, newPin: "", cardId: null, dialogOpen: false });
  };

  const [pendingCard, setPendingCard] = useState<PartialBy<NewCardRequest, "color" | "pin"> | null>(null);

  const handleAddCard = async (
    cardRequest: PartialBy<NewCardRequest, "color" | "pin">
  ) => {
    if (hitlEnabled) {
      setPendingCard(cardRequest);
      return;
    }
    void addNewCard({
      ...cardRequest,
      color: CARD_COLORS[cardRequest.type],
      pin: randomDigits(4).toString(),
    });
  };

  const confirmPendingCard = async () => {
    if (!pendingCard) return;
    await addNewCard({
      ...pendingCard,
      color: CARD_COLORS[pendingCard.type],
      pin: randomDigits(4).toString(),
    });
    setPendingCard(null);
  };

  // Add new card — standard mode (no HITL)
  useCopilotAction({
    name: "addNewCard",
    description: "Add new credit card",
    disabled: hitlEnabled || !PERMISSIONS.ADD_CARD.includes(currentUser.role),
    parameters: [
      {
        name: "type",
        type: "string",
        description: "The type of the card (set by user), Visa or Mastercard",
        required: true,
      },
      {
        name: "color",
        type: "string",
        description:
          "The color of the card (generated by copilot, bg-blue-500 for visa, bg-red-500 for mastercard)",
        required: true,
      },
      {
        name: "pin",
        type: "string",
        description: "The pin code of the card (set by user), 4 digits",
        required: true,
      },
    ],
    handler: async ({ type, color, pin }) => {
      await addNewCard({ type, color, pin } as NewCardRequest);
    },
  }, [hitlEnabled]);

  // Add new card — HITL mode (requires approval in chat)
  useCopilotAction({
    name: "addNewCardWithApproval",
    description: "Add new credit card (requires user approval)",
    disabled: !hitlEnabled || !PERMISSIONS.ADD_CARD.includes(currentUser.role),
    parameters: [
      {
        name: "type",
        type: "string",
        description: "The type of the card (set by user), Visa or Mastercard",
        required: true,
      },
      {
        name: "color",
        type: "string",
        description:
          "The color of the card (generated by copilot, bg-blue-500 for visa, bg-red-500 for mastercard)",
        required: true,
      },
      {
        name: "pin",
        type: "string",
        description: "The pin code of the card (set by user), 4 digits",
        required: true,
      },
    ],
    renderAndWait: ({ args, handler, status }) => {
      const { type, color, pin } = args;

      if (status === "inProgress") {
        return <div className="text-sm text-gray-500">Preparing card details...</div>;
      }

      return (
        <div className="p-4 border rounded-lg space-y-3 bg-white shadow-sm">
          <h3 className="font-semibold text-lg">Confirm New Card</h3>
          <div className="text-sm space-y-1">
            <p><span className="font-medium">Type:</span> {type}</p>
            <p><span className="font-medium">PIN:</span> {pin}</p>
          </div>
          <div className="flex gap-2 pt-2">
            <button
              className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded text-sm transition-colors"
              onClick={async () => {
                await addNewCard({ type, color, pin } as NewCardRequest);
                handler?.("Card created successfully");
              }}
            >
              Approve
            </button>
            <button
              className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded text-sm transition-colors"
              onClick={() => handler?.("Card creation denied by user")}
            >
              Deny
            </button>
          </div>
        </div>
      );
    },
  }, [hitlEnabled]);

  useCopilotAction({
    name: "assignPolicyToCard",
    description: "Assign a policy to a card",
    disabled: !PERMISSIONS.ADD_POLICY.includes(currentUser.role),
    parameters: [
      {
        name: "cardId",
        type: "string",
        description: "The card (from existing) to assign policy to",
        required: true,
      },
      {
        name: "policyType",
        type: "string",
        description: "The type of the policy to use",
        required: true,
      },
    ],
    handler: async ({ cardId, policyType }) => {
      const policyId = policies.find(
        (policy) => policy.type === policyType
      )?.id;
      if (!policyId)
        throw new Error("Could not find matching policy to assign");
      await assignPolicyToCard({ cardId, policyId });
    },
  });

  useCopilotAction({
    name: "addNoteToTransaction",
    description: "Add note to transaction",
    disabled: !PERMISSIONS.ADD_NOTE.includes(currentUser.role),
    parameters: [
      {
        name: "transactionId",
        type: "string",
        description: "The transaction to add note to (ID provided by copilot)",
        required: true,
      },
      {
        name: "content",
        type: "string",
        description: "The content of the note",
        required: true,
      },
    ],
    handler: addNoteToTransaction,
  });

  // Showcase usage of generative UI. The only co pilot related that's not in actions, due to usage of TSX
  useCopilotAction({
    name: "showTransactions",
    description:
      "Displays a list of transactions upon request. At least one parameter is required per request",
    disabled: !PERMISSIONS.SHOW_TRANSACTIONS.includes(currentUser.role),
    followUp: false,
    parameters: [
      {
        name: "card4Digits",
        type: "string",
        description: "the last 4 digits of the card",
        required: false,
      },
      {
        name: "policyId",
        type: "string",
        description: "the id of the policy (figured out by copilot)",
        required: false,
      },
      {
        name: "transactionTitle",
        type: "string",
        description: "the title of the transaction",
        required: false,
      },
    ],
    handler: async () => {
      await new Promise((resolve) => setTimeout(resolve, 3000));
    },
    render: ({ status, args }) => {
      const { card4Digits, policyId, transactionTitle } = args;

      let filteredTransactions = transactions;
      if (card4Digits) {
        filteredTransactions = filterTransactionsByCardLast4(
          transactions,
          cards,
          card4Digits
        );
      } else if (policyId) {
        filteredTransactions = filterTransactionsByPolicyId(
          transactions,
          policyId
        );
      } else if (transactionTitle) {
        filteredTransactions = filterTransactionByTitle(
          transactions,
          transactionTitle
        );
      }

      if (status === "inProgress") {
        return "Loading...";
      } else if (!filteredTransactions) {
        return "Problem fetching transactions";
      } else {
        return <TransactionsList transactions={filteredTransactions} compact />;
      }
    },
  });

  // Enable pin changing with co pilot
  useCopilotAction({
    name: "setCardPin",
    description: "Set the pin code of an existing card",
    disabled: !PERMISSIONS.SET_PIN.includes(currentUser.role),
    parameters: [
      {
        name: "cardId",
        type: "string",
        description: "The id of the card (provided by copilot)",
        required: true,
      },
    ],
    handler: async ({ cardId }) => {
      dispatch({ dialogOpen: true, cardId });
    },
  });

  useCopilotAction({
    name: "showAndApproveTransactions",
    description: `
      This operation is per department.
      An executive department admin is allowed to approve/deny from other departments as well
      
      Show the unapproved transactions and allow the admin per department to approve them.
      
      Transactions will be presented to the admin one by one
    `,
    disabled: !PERMISSIONS.APPROVE_TRANSACTION.includes(currentUser.role),
    parameters: [
      {
        name: "transactionId",
        type: "string",
        description:
          "The id of pending transaction to present to the given department admin (provided by copilot)",
        required: true,
      },
    ],
    renderAndWait: ({ args, handler, status }) => {
      const { transactionId } = args;
      if (status === "inProgress") {
        return <div>Loading...</div>;
      }

      if (!transactionId) {
        handler?.(
          "A transaction ID was not given, could be that there arent any pending approval or there was an error"
        );
        return <div>No pending transactions</div>;
      }

      async function handleChangeTransactionStatus({
        id,
        status,
      }: {
        id: string;
        status: Transaction["status"];
      }) {
        await changeTransactionStatus({ id, status });
        handler?.(`transaction ${id} ${status}`);
      }

      return (
        <TransactionsList
          transactions={transactions.filter((t) =>
            transactionId.includes(t.id)
          )}
          showApprovalInterface
          approvalInterfaceProps={{
            onApprove: (transactionId) =>
              handleChangeTransactionStatus({
                id: transactionId,
                status: "approved",
              }),
            onDeny: (transactionId) =>
              handleChangeTransactionStatus({
                id: transactionId,
                status: "denied",
              }),
          }}
        />
      );
    },
  });

  useCopilotReadable({
    description:
      "The user does not have permission to perform these actions." +
      "If they ask you to do one of these, please tell them that they " +
      "do not have permission to do so." +
      "Do not tell them they are on the wrong page, the real reason " +
      "is that they do not have permission to perform the action.",
    value: Object.keys(PERMISSIONS).filter(
      (key) =>
        !PERMISSIONS[key as keyof typeof PERMISSIONS].includes(currentUser.role)
    ),
  });

  // useCopilotReadable({
  //   description: "The user has access to the following documents",
  //   value: PERMISSIONS.READ_MSA.includes(currentUser.role) ? [FEDEX_MSA] : [],
  // });

  

  if (!cards || !policies) return null;

  return (
    <div className="container mx-auto p-6">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold">Credit Cards</h1>
        <div className="flex items-center gap-4">
          <label className="flex items-center gap-2 cursor-pointer select-none">
            <span className="text-sm font-medium text-gray-700">
              Human-in-the-Loop
            </span>
            <button
              role="switch"
              aria-checked={hitlEnabled}
              onClick={() => setHitlEnabled(!hitlEnabled)}
              className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                hitlEnabled ? "bg-green-600" : "bg-gray-300"
              }`}
            >
              <span
                className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                  hitlEnabled ? "translate-x-6" : "translate-x-1"
                }`}
              />
            </button>
          </label>
          <AddCardDropdown
            handleAddCard={handleAddCard}
            currentUser={currentUser}
          />
        </div>
      </div>
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {cards.length ? (
          cards.map((card) => (
            <CreditCardDetails
              key={card.id}
              card={card}
              policy={policies.find((p) => p.id === card.expensePolicyId)}
              onChangePinModalOpen={() =>
                dispatch({ dialogOpen: true, cardId: card.id })
              }
            />
          ))
        ) : (
          <div>No cards found for {currentUser.team} team</div>
        )}
      </div>

      <ChangePinDialog
        dialogOpen={state.dialogOpen}
        onSubmit={({ pin, cardId }) => handleChangePinSubmit({ pin, cardId })}
        loading={state.loading}
        onDialogOpenChange={(open) => dispatch({ dialogOpen: open })}
        cards={cards}
      />

      {pendingCard && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 shadow-xl max-w-sm w-full mx-4 space-y-4">
            <h3 className="font-semibold text-lg">Confirm New Card</h3>
            <div className="text-sm space-y-1">
              <p><span className="font-medium">Type:</span> {pendingCard.type}</p>
            </div>
            <div className="flex gap-2 justify-end pt-2">
              <button
                className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded text-sm transition-colors"
                onClick={confirmPendingCard}
              >
                Approve
              </button>
              <button
                className="bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded text-sm transition-colors"
                onClick={() => setPendingCard(null)}
              >
                Deny
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
