"use client";

import { useEffect, useReducer } from "react";
import { useCopilotAction, useCopilotReadable } from "@copilotkit/react-core";
import {
  CARD_COLORS,
  CardBrand,
  NewCardRequest,
  Transaction,
} from "@/app/api/v1/data";
import { CreditCardDetails } from "@/components/credit-card-details";
import { PartialBy } from "@/lib/type-helpers";
import {
  filterTransactionByTitle,
  filterTransactionsByCardLast4,
  filterTransactionsByPolicyId,
  randomDigits,
} from "@/lib/utils";
import useCreditCards from "@/app/actions";
import { useAuthContext } from "@/components/auth-context";
import { AddCardDropdown } from "@/components/add-card-dropdown";
import { TransactionsList } from "@/components/transactions-list";
import { ChangePinDialog } from "@/components/change-pin-dialog";
import { useSearchParams } from "next/navigation";
import { CardsPageOperations } from "@/components/copilot-context";
import { useCopilotChatSuggestions } from "@copilotkit/react-ui";
import { PERMISSIONS } from "@/app/api/v1/permissions";

interface ChangePinState {
  newPin: string;
  dialogOpen: boolean;
  cardId: string | null;
  loading: boolean;
}

export default function Page() {
  const { currentUser } = useAuthContext();
  const searchParams = useSearchParams();
  const operation = searchParams.get("operation") as CardsPageOperations | null;
  const [state, dispatch] = useReducer<
    React.Reducer<ChangePinState, Partial<ChangePinState>>
  >(
    (state: ChangePinState, payload: Partial<ChangePinState>) => ({
      ...state,
      ...payload,
    }),
    { newPin: "", dialogOpen: false, cardId: null, loading: false }
  );
  const {
    cards,
    policies,
    transactions,
    addNewCard,
    changePin,
    assignPolicyToCard,
    addNoteToTransaction,
    changeTransactionStatus,
  } = useCreditCards();

  useEffect(() => {
    const operationNameToMethod: Partial<
      Record<CardsPageOperations, () => void>
    > = {
      [CardsPageOperations.ChangePin]: () => dispatch({ dialogOpen: true }),
    };

    if (!operation || !Object.values(CardsPageOperations).includes(operation))
      return;
    operationNameToMethod[operation]?.();
  }, [operation]);

  const handleChangePinSubmit = async ({
    pin,
    cardId,
  }: {
    pin?: string;
    cardId?: string;
  }) => {
    dispatch({ loading: true });
    await changePin({
      pin: pin ?? state.newPin,
      cardId: cardId ?? state.cardId!,
    });
    dispatch({ loading: false, newPin: "", cardId: null, dialogOpen: false });
  };

  const handleAddCard = async (
    cardRequest: PartialBy<NewCardRequest, "color" | "pin">
  ) => {
    void addNewCard({
      ...cardRequest,
      color: CARD_COLORS[cardRequest.type],
      pin: randomDigits(4).toString(),
    });
  };

  // Enable add new card with co pilot (human-in-the-loop)
  useCopilotAction({
    name: "addNewCard",
    description: "Add new credit card. Always show the card details for user approval before creating.",
    disabled: !PERMISSIONS.ADD_CARD.includes(currentUser.role),
    parameters: [
      {
        name: "type",
        type: "string",
        description: "The type of the card (set by user), Visa or Mastercard",
        required: true,
      },
      {
        name: "color",
        type: "string",
        description:
          "The color of the card (generated by copilot, bg-blue-500 for visa, bg-red-500 for mastercard)",
        required: true,
      },
      {
        name: "pin",
        type: "string",
        description: "The pin code of the card (set by user), 4 digits",
        required: true,
      },
    ],
    renderAndWait: ({ args, handler, status }) => {
      const { type, color, pin } = args;

      if (status === "inProgress") {
        return <div>Loading...</div>;
      }

      return (
        <div className="rounded-lg border bg-white p-4 shadow-sm space-y-4">
          <h3 className="font-semibold text-lg">New Card Request</h3>
          <div className="flex items-center gap-3">
            <div className="bg-white border rounded-md p-1 flex items-center justify-center w-10 h-7">
              {type === CardBrand.Visa ? (
                <svg className="h-5" viewBox="0 0 780 500" xmlns="http://www.w3.org/2000/svg">
                  <path d="M293.2 348.7l33.4-195.8h53.4l-33.4 195.8zM540.7 157.2c-10.6-4-27.2-8.3-47.9-8.3-52.8 0-90 26.6-90.2 64.6-.3 28.1 26.5 43.8 46.8 53.2 20.8 9.6 27.8 15.7 27.7 24.3-.1 13.1-16.6 19.1-32 19.1-21.4 0-32.7-3-50.3-10.2l-6.9-3.1-7.5 43.8c12.5 5.5 35.6 10.2 59.6 10.5 56.2 0 92.6-26.3 93-66.8.2-22.3-14-39.2-44.8-53.2-18.6-9.1-30.1-15.1-30-24.3 0-8.1 9.7-16.8 30.6-16.8 17.4-.3 30.1 3.5 39.9 7.5l4.8 2.3 7.2-42.7zM676.3 152.9h-41.3c-12.8 0-22.4 3.5-28 16.3l-79.4 179.5h56.2s9.2-24.2 11.3-29.5c6.1 0 60.8.1 68.6.1 1.6 6.9 6.5 29.4 6.5 29.4h49.7l-43.6-195.8zm-65.8 126.3c4.4-11.3 21.4-54.8 21.4-54.8-.3.5 4.4-11.4 7.1-18.8l3.6 17s10.3 47 12.4 56.6h-44.5zM232.2 152.9L180 283.6l-5.6-27c-9.7-31.2-39.9-65-73.7-81.9l47.9 173.8h56.6l84.2-195.6h-57.2" fill="#1a1f71"/>
                  <path d="M131.9 152.9H46.3l-.7 3.8c67.1 16.2 111.5 55.4 129.9 102.5L157.2 169c-3.2-12.5-12.7-15.7-25.3-16.1" fill="#f7a600"/>
                </svg>
              ) : (
                <svg className="h-5" viewBox="0 0 780 500" xmlns="http://www.w3.org/2000/svg">
                  <circle cx="312" cy="250" r="200" fill="#eb001b"/>
                  <circle cx="468" cy="250" r="200" fill="#f79e1b"/>
                  <path d="M390 100.2c-49.7 38.3-81.6 98.1-81.6 165.8s31.9 127.5 81.6 165.8c49.7-38.3 81.6-98.1 81.6-165.8S439.7 138.5 390 100.2z" fill="#ff5f00"/>
                </svg>
              )}
            </div>
            <div>
              <p className="font-medium">{type}</p>
              <p className="text-sm text-gray-500">PIN: {pin}</p>
            </div>
          </div>
          <div className="flex gap-2">
            <button
              className="flex-1 rounded-md bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700"
              onClick={async () => {
                await addNewCard({ type, color, pin } as NewCardRequest);
                handler?.("Card created successfully");
              }}
            >
              Approve
            </button>
            <button
              className="flex-1 rounded-md bg-gray-200 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-300"
              onClick={() => handler?.("Card creation denied by user")}
            >
              Deny
            </button>
          </div>
        </div>
      );
    },
  });

  useCopilotAction({
    name: "assignPolicyToCard",
    description: "Assign a policy to a card",
    disabled: !PERMISSIONS.ADD_POLICY.includes(currentUser.role),
    parameters: [
      {
        name: "cardId",
        type: "string",
        description: "The card (from existing) to assign policy to",
        required: true,
      },
      {
        name: "policyType",
        type: "string",
        description: "The type of the policy to use",
        required: true,
      },
    ],
    renderAndWait: ({ args, handler, status }) => {
      const { cardId, policyType } = args;

      if (status === "inProgress") {
        return <div>Loading...</div>;
      }

      const card = cards.find((c) => c.id === cardId);
      const policy = policies.find((p) => p.type === policyType);

      return (
        <div className="rounded-lg border bg-white p-4 shadow-sm space-y-4">
          <h3 className="font-semibold text-lg">Assign Policy to Card</h3>
          <div className="text-sm space-y-1">
            <p><span className="text-gray-500">Card:</span> {card ? `${card.type} ending in ${card.last4}` : cardId}</p>
            <p><span className="text-gray-500">Policy:</span> {policyType}</p>
          </div>
          <div className="flex gap-2">
            <button
              className="flex-1 rounded-md bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700"
              onClick={async () => {
                const policyId = policy?.id;
                if (!policyId) {
                  handler?.("Could not find matching policy to assign");
                  return;
                }
                await assignPolicyToCard({ cardId, policyId });
                handler?.("Policy assigned successfully");
              }}
            >
              Approve
            </button>
            <button
              className="flex-1 rounded-md bg-gray-200 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-300"
              onClick={() => handler?.("Policy assignment denied by user")}
            >
              Deny
            </button>
          </div>
        </div>
      );
    },
  });

  useCopilotAction({
    name: "addNoteToTransaction",
    description: "Add note to transaction",
    disabled: !PERMISSIONS.ADD_NOTE.includes(currentUser.role),
    parameters: [
      {
        name: "transactionId",
        type: "string",
        description: "The transaction to add note to (ID provided by copilot)",
        required: true,
      },
      {
        name: "content",
        type: "string",
        description: "The content of the note",
        required: true,
      },
    ],
    renderAndWait: ({ args, handler, status }) => {
      const { transactionId, content } = args;

      if (status === "inProgress") {
        return <div>Loading...</div>;
      }

      const transaction = transactions.find((t) => t.id === transactionId);

      return (
        <div className="rounded-lg border bg-white p-4 shadow-sm space-y-4">
          <h3 className="font-semibold text-lg">Add Note to Transaction</h3>
          <div className="text-sm space-y-1">
            <p><span className="text-gray-500">Transaction:</span> {transaction?.title ?? transactionId}</p>
            <p><span className="text-gray-500">Note:</span> {content}</p>
          </div>
          <div className="flex gap-2">
            <button
              className="flex-1 rounded-md bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700"
              onClick={async () => {
                await addNoteToTransaction({ transactionId, content });
                handler?.("Note added successfully");
              }}
            >
              Approve
            </button>
            <button
              className="flex-1 rounded-md bg-gray-200 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-300"
              onClick={() => handler?.("Note addition denied by user")}
            >
              Deny
            </button>
          </div>
        </div>
      );
    },
  });

  // Showcase usage of generative UI. The only co pilot related that's not in actions, due to usage of TSX
  useCopilotAction({
    name: "showTransactions",
    description:
      "Displays a list of transactions upon request. At least one parameter is required per request",
    disabled: !PERMISSIONS.SHOW_TRANSACTIONS.includes(currentUser.role),
    followUp: false,
    parameters: [
      {
        name: "card4Digits",
        type: "string",
        description: "the last 4 digits of the card",
        required: false,
      },
      {
        name: "policyId",
        type: "string",
        description: "the id of the policy (figured out by copilot)",
        required: false,
      },
      {
        name: "transactionTitle",
        type: "string",
        description: "the title of the transaction",
        required: false,
      },
    ],
    handler: async () => {
      await new Promise((resolve) => setTimeout(resolve, 3000));
    },
    render: ({ status, args }) => {
      const { card4Digits, policyId, transactionTitle } = args;

      let filteredTransactions = transactions;
      if (card4Digits) {
        filteredTransactions = filterTransactionsByCardLast4(
          transactions,
          cards,
          card4Digits
        );
      } else if (policyId) {
        filteredTransactions = filterTransactionsByPolicyId(
          transactions,
          policyId
        );
      } else if (transactionTitle) {
        filteredTransactions = filterTransactionByTitle(
          transactions,
          transactionTitle
        );
      }

      if (status === "inProgress") {
        return "Loading...";
      } else if (!filteredTransactions) {
        return "Problem fetching transactions";
      } else {
        return <TransactionsList transactions={filteredTransactions} compact />;
      }
    },
  });

  // Enable pin changing with co pilot
  useCopilotAction({
    name: "setCardPin",
    description: "Set the pin code of an existing card",
    disabled: !PERMISSIONS.SET_PIN.includes(currentUser.role),
    parameters: [
      {
        name: "cardId",
        type: "string",
        description: "The id of the card (provided by copilot)",
        required: true,
      },
    ],
    renderAndWait: ({ args, handler, status }) => {
      const { cardId } = args;

      if (status === "inProgress") {
        return <div>Loading...</div>;
      }

      const card = cards.find((c) => c.id === cardId);

      return (
        <div className="rounded-lg border bg-white p-4 shadow-sm space-y-4">
          <h3 className="font-semibold text-lg">Change Card PIN</h3>
          <div className="text-sm space-y-1">
            <p><span className="text-gray-500">Card:</span> {card ? `${card.type} ending in ${card.last4}` : cardId}</p>
          </div>
          <div className="flex gap-2">
            <button
              className="flex-1 rounded-md bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700"
              onClick={() => {
                dispatch({ dialogOpen: true, cardId });
                handler?.("PIN change dialog opened");
              }}
            >
              Approve
            </button>
            <button
              className="flex-1 rounded-md bg-gray-200 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-300"
              onClick={() => handler?.("PIN change denied by user")}
            >
              Deny
            </button>
          </div>
        </div>
      );
    },
  });

  useCopilotAction({
    name: "showAndApproveTransactions",
    description: `
      This operation is per department.
      An executive department admin is allowed to approve/deny from other departments as well
      
      Show the unapproved transactions and allow the admin per department to approve them.
      
      Transactions will be presented to the admin one by one
    `,
    disabled: !PERMISSIONS.APPROVE_TRANSACTION.includes(currentUser.role),
    parameters: [
      {
        name: "transactionId",
        type: "string",
        description:
          "The id of pending transaction to present to the given department admin (provided by copilot)",
        required: true,
      },
    ],
    renderAndWait: ({ args, handler, status }) => {
      const { transactionId } = args;
      if (status === "inProgress") {
        return <div>Loading...</div>;
      }

      if (!transactionId) {
        handler?.(
          "A transaction ID was not given, could be that there arent any pending approval or there was an error"
        );
        return <div>No pending transactions</div>;
      }

      async function handleChangeTransactionStatus({
        id,
        status,
      }: {
        id: string;
        status: Transaction["status"];
      }) {
        await changeTransactionStatus({ id, status });
        handler?.(`transaction ${id} ${status}`);
      }

      return (
        <TransactionsList
          transactions={transactions.filter((t) =>
            transactionId.includes(t.id)
          )}
          showApprovalInterface
          approvalInterfaceProps={{
            onApprove: (transactionId) =>
              handleChangeTransactionStatus({
                id: transactionId,
                status: "approved",
              }),
            onDeny: (transactionId) =>
              handleChangeTransactionStatus({
                id: transactionId,
                status: "denied",
              }),
          }}
        />
      );
    },
  });

  useCopilotReadable({
    description:
      "The user does not have permission to perform these actions." +
      "If they ask you to do one of these, please tell them that they " +
      "do not have permission to do so." +
      "Do not tell them they are on the wrong page, the real reason " +
      "is that they do not have permission to perform the action.",
    value: Object.keys(PERMISSIONS).filter(
      (key) =>
        !PERMISSIONS[key as keyof typeof PERMISSIONS].includes(currentUser.role)
    ),
  });

  // useCopilotReadable({
  //   description: "The user has access to the following documents",
  //   value: PERMISSIONS.READ_MSA.includes(currentUser.role) ? [FEDEX_MSA] : [],
  // });

  

  if (!cards || !policies) return null;

  return (
    <div className="container mx-auto p-6">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold">Credit Cards</h1>
        <AddCardDropdown
          handleAddCard={handleAddCard}
          currentUser={currentUser}
        />
      </div>
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {cards.length ? (
          cards.map((card) => (
            <CreditCardDetails
              key={card.id}
              card={card}
              policy={policies.find((p) => p.id === card.expensePolicyId)}
              onChangePinModalOpen={() =>
                dispatch({ dialogOpen: true, cardId: card.id })
              }
            />
          ))
        ) : (
          <div>No cards found for {currentUser.team} team</div>
        )}
      </div>

      <ChangePinDialog
        dialogOpen={state.dialogOpen}
        onSubmit={({ pin, cardId }) => handleChangePinSubmit({ pin, cardId })}
        loading={state.loading}
        onDialogOpenChange={(open) => dispatch({ dialogOpen: open })}
        cards={cards}
      />
    </div>
  );
}
